package com.ss.staysafe;

import android.os.Bundle;
import android.app.Activity;
import android.text.Html;
import android.view.Menu;
import android.webkit.WebView;
import android.widget.TextView;
public class Help extends Activity {
	
	TextView tv;
	
	@Override
	protected void onStart() {
		// TODO Auto-generated method stub

		super.onStart();
	}

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_help);
		
		String text = "<html><body style=\"text-align:justify\"> %s </body></Html>";
		String data = "<br/>Stay Safe 365 will help you to stay connected with all your dear ones in the times of emergency!<br/><br/><br/>1. For adding a person to your emergency contact list, go to the 'Contacts' option and select the contact or you can enter the number yourself. You can select up to five emergency contacts. <br/><br/>2. For enabling message sending (along with your current location), go to the 'Settings' option and check the 'Message' checkbox.<br/><br/>3. For enabling alarm, go to the 'Settings' option and check the 'Alarm' checkbox. And once the alarm starts, it will go on for 45 seconds without stopping, for your own safety!<br/><br/>4. For enabling flashlight, go to the 'Settings' option and check the 'Flash' checkbox.  And once the flashlight starts, it will go on for 45 seconds without stopping, for your own safety! (If your phone does not have flash, please do not turn on this feature.)<br/><br/>5. For enabling the 20 seconds video recording feature (works when the alarm and flash have gone off for a minute and stopped), go to the 'Settings' option and click on the 'Video' checkbox. The recording will be saved on your device in a folder named 'Stay Safe Videos'.<br/><br/>6. Select any or all of the above options as you wish and you are good to go. Just press the 'Start' button and there's your safety device at any time!<br/><br/>7. To receive a dummy call anytime, go to the 'Fake Call' option and enter a name or a specific number in the box and then select the time interval after which you want to receive the 'call'. If you do not enter any number, a random phone number will be generated by the application. You need not call that number back!! :D";

		WebView webView = (WebView) findViewById(R.id.webView1);
		webView.loadData(String.format(text, data), "text/html", "utf-8");
	}

}